[build]
  base = "client"
  publish = "client/build"
  command = "npm install && npm run build"

[dev]
  command = "npm start --prefix client"
  port = 8888

[build.environment]
  NODE_VERSION = "18"
